   "gaadi": "https://youtu.be/xrsgfT1c9jQ?si=FCjpAj2bQc4JcxjU", 
    "jamila": "https://youtu.be/wsWIYhPjMAs?si=eQnSSIZAZ8J9mEZ8",
    "mehbooba": "https://youtu.be/9yg_61lU7t8?si=ek65vXswplopn4v1",
    "bairi": "https://youtu.be/yXxov9HJN9A?si=pyJJP9P_OTN7iRfs",
    "supreme": "https://youtu.be/AX1zRInC_TA?si=fuyVs2Zk8NvRgog2",
    "aadat": "https://youtu.be/lcw4TDMBjZA?si=LMhi_AiVEvhSh1U9",
    "chillgum": "https://youtu.be/cTokGAQAaK4?si=1Wqb4SkKT_80gFBr",
    "status": "https://youtu.be/A7Dk-ixHKjY?si=TiaHx7f2gsbWJyZT",
    "kalakar": "https://youtu.be/KhnVcAC5bIM?si=PdaQheBAzeMPxOVp",
}
